# Generated by Django 5.2.4 on 2025-08-01 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_partic_remove_room_host_remove_room_topic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
