# Generated by Django 5.2.4 on 2025-08-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='visit_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='ip_address',
            field=models.GenericIPAddressField(unique=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visited_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
