# Generated by Django 5.2.4 on 2025-08-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_visitor_visit_count_alter_visitor_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='item_ids',
            field=models.TextField(blank=True, default=''),
        ),
    ]
