# Generated by Django 5.2.4 on 2025-08-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_visitor_item_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='item_ids',
            field=models.TextField(blank=True, null=True),
        ),
    ]
